### ISSUE TITLE
Warning: React.jsx

### ISSUE THREAD

**Issue by wkylin** [marcveens/react-drawio#3]
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by marcveens** [comment]
Thanks for reporting this issue! I forgot to update the readme with the correct import, so I just changed it. No need for updating the package, you need to import `DrawIoEmbed` instead of `DiagramsEmbed`. 

Here's a working example: 
- JS: https://codesandbox.io/s/naughty-bird-nljk2c?file=/src/App.js
- TS: https://codesandbox.io/s/still-snow-nqxpj2?file=/src/App.tsx
